### ISSUE TITLE
Faker gem occasionally causes errors in spec

### ISSUE THREAD

**Issue by helloeduardo** [helloeduardo/adopt_dont_shop_paired#47]
In test: As a visitor When I visit a Users show page I cannot see reviews from deleted shelters
   - Failure/Error: expect(page).to_not have_content(review2.content)
   - Failure/Error: expect(page).to_not have_content(review2.title)

May have to override content/title in test to be unique and non-duplicated.

**Comment by katemorris** [comment]
Will be fixed in upcoming PR called test_check_fakr
